# This config should be placed in following path:
#   %AppData%\Parity\Ethereum\config.toml

[parity]
# Custom chain
chain = "krwcoin-v2.2.json"
# No updates will be auto-installed
auto_update = "none"
# Blockchain and settings will be stored in data.
base_path = "data"

[network]
# Override the bootnodes from selected chain file.
# reserved_peers = "C:\\Users\user\\works\\chainworks\\reserved-bootnodes-v2.1.txt"
reserved_peers = "reserved-bootnodes-v2.2.txt"

[rpc]
# Allows Cross-Origin Requests from domain ''.
cors = ["*"]


[mining]
# Account address to receive reward when block is mined.
author = "0x0c7a4D71DB35451c80bBB03eaf24549897b99cdA"
extra_data = "Class3 Eunjoo"

[footprint]
# Compute and Store tracing data. (Enables trace_* APIs).
tracing = "on"
# Keep all state trie data. No pruning.
pruning = "archive"
# Enables Fat DB
fat_db = "on"